# Generated by Django 5.0.1 on 2024-02-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_achievementandaward_activity_interest_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinformation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
