# Generated by Django 5.0.1 on 2024-02-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_basicinformation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherskill',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True),
        ),
    ]
